# Generated by Django 4.0 on 2023-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_internalpayment_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internalpayment',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
