# Generated by Django 4.0 on 2023-02-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_deposit_time_added_internalpayment_time_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.member'),
        ),
    ]
